config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  root "static#home"
  post :sso_account_verification, to: "saml#sso_account_verification", as: :sso_account_verification
  # post :consume
  post "auth/sso/callback", to: "saml#consume"
  devise_for :users

  # post "auth/okta/callback", to: "static#okta"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  def self.get_saml_settings
    testing = self.first
    idp_metadata_parser = OneLogin::RubySaml::IdpMetadataParser.new
    settings = idp_metadata_parser.parse(testing.content)
    settings
  end

  def get_saml_settings
    idp_metadata_parser = OneLogin::RubySaml::IdpMetadataParser.new
    settings = idp_metadata_parser.parse(self.content)
    settings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:email, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/saml_controller.rb
class SamlController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:consume, :logout]

  def sso_account_verification
    unless params[:email].present?
      redirect_to root_path
      return
    end

    account = Account.find_by email: params[:email]
    if account
      settings = account.get_saml_settings
      if settings.nil?
        render :action => :no_settings
        return
      end

      request = OneLogin::RubySaml::Authrequest.new
      redirect_to(request.create(settings, RelayState: 1234567))
    else
      # to do show flash message
      redirect_to root_path
    end
  end

  def consume
    settings = Account.get_saml_settings
    if settings.nil?
      render :action => :no_settings
      return
    end
    response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], skip_recipient_check: true)
    response.settings = settings

    if response.is_valid?
      # sign in or sign up here
      # render :action => :index
      # sign_in
      user = User.find_by email: response.attributes["email"]
      if !user
        user = User.create email: response.attributes["email"], password: Devise.friendly_token[0,20]
      end

      sign_in(user)

      # binding.pry

      redirect_to root_path
    else
      logger.info "Response Invalid. Errors: #{response.errors}"
      @errors = response.errors
      render :action => :fail
    end
    # binding.pry
  end

  def metadata
    settings = Account.get_saml_settings
    meta = OneLogin::RubySaml::Metadata.new
    render xml: meta.generate(settings, true)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:okta]
  def home
  end

  def okta
    binding.pry
    # params[:RelayState]
    response = OneLogin::RubySaml::Response.new(params[:SAMLResponse])
    settings = Account.get_saml_settings
    response.settings = settings
    if response.is_valid?
    else
      logger.info "Response Invalid. Errors: #{response.errors}"
      @errors = response.errors
      render :action => :fail
    end
    # binding.pry
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/saml_helper.rb
module SamlHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>
<%= link_to "Go home", root_path %>

<% @accounts.each do |account| %>
  <p><%= account.email %></p>
  <pre><%= account.content %></pre>
  <p><%= link_to 'Show', account %></p>
  <p><%= link_to 'Edit', edit_account_path(account) %></p>
  <p><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @account.content %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSOSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>